// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpo7f4mcENiVkPNZWk-ktEIXQkapLw7Y',
    appId: '1:165965728236:web:2d243fb30788f700c958c9',
    messagingSenderId: '165965728236',
    projectId: 'masterfirebase-943a9',
    authDomain: 'masterfirebase-943a9.firebaseapp.com',
    storageBucket: 'masterfirebase-943a9.firebasestorage.app',
    measurementId: 'G-VNGX03FHBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo35-ZojJ3vywuo8UwufNg437ITdRcvmA',
    appId: '1:165965728236:android:64ba5caff13713e5c958c9',
    messagingSenderId: '165965728236',
    projectId: 'masterfirebase-943a9',
    storageBucket: 'masterfirebase-943a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD60zatrmdpx-A1w2HDeocXfMxgX9LUAXs',
    appId: '1:165965728236:ios:acd26802b2b204d3c958c9',
    messagingSenderId: '165965728236',
    projectId: 'masterfirebase-943a9',
    storageBucket: 'masterfirebase-943a9.firebasestorage.app',
    iosBundleId: 'com.example.teamFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD60zatrmdpx-A1w2HDeocXfMxgX9LUAXs',
    appId: '1:165965728236:ios:acd26802b2b204d3c958c9',
    messagingSenderId: '165965728236',
    projectId: 'masterfirebase-943a9',
    storageBucket: 'masterfirebase-943a9.firebasestorage.app',
    iosBundleId: 'com.example.teamFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtpo7f4mcENiVkPNZWk-ktEIXQkapLw7Y',
    appId: '1:165965728236:web:1c0848afe78f80bcc958c9',
    messagingSenderId: '165965728236',
    projectId: 'masterfirebase-943a9',
    authDomain: 'masterfirebase-943a9.firebaseapp.com',
    storageBucket: 'masterfirebase-943a9.firebasestorage.app',
    measurementId: 'G-9H0EL5XYDH',
  );
}
